### ISSUE TITLE
midje.emission.deprecation/deprecate & without-previous-deprecations doesn't seem to be used

### ISSUE THREAD

**Issue by muhuk** [marick/Midje#312]
It seems they can be safely removed.

**Comment by marick** [comment]
I'd be more inclined to split them off as a generic deprecation library. (If they're good enough for that - I don't remember.)

**Comment by muhuk** [comment]
Sure. 

I prefer just marking vars as `^:deprecated` (and then maybe process this via lein plugins etc.).

I'm closing this for now.

**Comment by marick** [comment]
Are there lein plugins that tell you if your code uses a var marked `:deprecated`? A quick search doesn't find one.

**Comment by muhuk** [comment]
I don't know of any. What I meant was processing metadata would be the way I'd go with this. It shouldn't be too hard to write a plugin (or hook).

[codox](https://github.com/weavejester/codox) uses `:deprecated` tags to show in API docs.

**Comment by marick** [comment]
In general, yes. I'm working from the assumption that a lot of people are like me: they need multiple reminders before they actually do something that's tedious or annoying (like removing the use of deprecated features). A separate `lein deprecations` wouldn't get used. That's why I built it into Midje.
