### ISSUE TITLE
Lein midje report it cant find template

### ISSUE THREAD

**Issue by favetelinguis** [marick/Midje#314]
Im getting the following message:

~/c/clojure ❯❯❯ lein new midje quux
Failed to resolve version for midje:lein-template:jar:RELEASE: Could not find metadata midje:lein-template/maven-metadata.xml in local (/home/henke/.m2/repository)
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
Could not find template midje on the classpath.

I have added the lein-midje plugin to ~/.lein/projects.clj. I have also tried rm -rf ~/.m2/reposotory
but still im getting this error. Not sure what to try next?

**Comment by marick** [comment]
What happens if you just do `lein midje`?

**Comment by favetelinguis** [comment]
'midje' is not a task. See 'lein help'.

I can get it working om OSx but in Linux im getting this error. Not sure what has happened?

**Comment by marick** [comment]
In that case, lein-midje . I generally put lein-midje in each project file, because I want my projects to be self-contained (so that other people can fork them, `lein midje` can run on the continuous integration server, etc). For example: https://github.com/marick/suchwow/blob/master/project.clj

Does that work for you?

**Comment by marick** [comment]
Adopting a policy of "if it hasn't happened by now, it will either happen in 2.0 or never", I'm closing this
