### ISSUE TITLE
notempty checker for sequentials

### ISSUE THREAD

**Issue by shmish111** [marick/Midje#330]
I find I use this quite a lot, could it be incorporated into midje?
```clj
(defchecker notempty
            "a list contains something"
            [actual]
            (not (empty? actual)))
```

**Comment by marick** [comment]
I could swear I responded to this - sorry.

My typical "what I wish were already in Clojure" contains a `not-empty?` https://github.com/marick/suchwow/blob/master/src/such/shorthand.clj#L45 Then I can not only use that predicate in my code (instead of the unnecessarily obscure `seq`), but I also can use it on the right-hand side of a check:

```clojure
user=> (fact [1] => not-empty?)
true
```

Lots of predicates that are useful in tests are also useful in product code.

**Comment by marick** [comment]
Note that the message is still nicely readable, even without `defchecker`:

```clojure
user=> (fact [] => not-empty?)

FAIL at (form-init4614054727114262727.clj:2)
Actual result did not agree with the checking function.
        Actual result: []
    Checking function: not-empty?
false
```

**Comment by shmish111** [comment]
OK, so you're suggesting that I implement `not-empty?` as a Clojure function (or use your library)? You can close this then as it won't be implemented.
