### ISSUE TITLE
Autotest do not stop tracking deleted files/namespaces

### ISSUE THREAD

**Issue by dlebrero** [marick/Midje#333]
When deleting (or renaming) a namespace, autotest does not stop tracking the deleted file and stops running.

The error report from Midje is:
LOAD FAILURE for deletedns
Could not locate deletedns.class or deletedns.clj

**Comment by marick** [comment]
I can't replicate this. Can you give me some details, perhaps using https://github.com/marick/sample-midje-project and a description of the sequence of edits/deletions needed to produce the error?

**Comment by dlebrero** [comment]
I have branched the sample project to https://github.com/dlebrero/sample-midje-project. 
To reproduce checkout 6f132a3ecb092d3304905fc5d56b93568d69212d (your repo before any change), run `lein midje :autotest` and then checkout one step at a time.

Thanks a lot.

**Comment by marick** [comment]
Sorry for the delay. I see that the sequence of steps is: 
1. create a test file that depends on existing file.
2. change that existing file.
3. delete the new test file.

If step 2 is left out, it doesn't fail. I don't immediately see why, because Midje uses `tools.namespace` in a way that was... orthogonal to its original purpose. I should check if it's become more general-purpose since it was created.

**Comment by marick** [comment]
I spent some time looking at the problem. The root cause is roughly this: I use `clojure.tools.namespace`. It's really tailored for use in the Component workflow, which is similar to - but not the same as - an autotest workflow. So I had difficulty interfacing with it. That difficulty led me to decide to ignore deleted files. 

In an ideal world, part of tools.namespace would generate a model of the current filesystem. That model could be used to (periodically and efficiently) generate a new model of the new filesystem state. There would be a function that, given two models, would do reloads as required to make the runtime match (roughly) the file system. It's the "roughly" that's the problem. When files are deleted, the Component workflow wants you to take explicit action to make it disappear from the runtime. Midje is less prescriptive: it is happy to just ignore deleted files and assume their residue in the runtime is harmless. If it's not, well, then, just start `autotest` again.

A less opinionated library would be a really nice addition to the Clojure ecosystem. [Bultitude](https://github.com/Raynes/bultitude) went some distance in that direction, though it seems to be more or less about Leiningen. 

In any case, I spent some time looking at the interface between Midje and `tools.namespace`, and I'm thinking I don't have time to fix this problem with confidence.

**Comment by dlebrero** [comment]
Thanks a lot for looking into this.

I have been playing around a bit and found that removing the deleted namespaces from the state-tracker dependencies seems to work for this particular issue. 

Here is a quick and dirty patch for the midje.data.project-state ns that does the trick:

```Clojure
(defn prepare-for-next-scan [state-tracker]
  (let [unloaded (clojure.set/difference (set (unload-key state-tracker))
                                         (set (load-key state-tracker)))
        state-tracker (assoc state-tracker
                             time-key (latest-modification-time state-tracker)
                             unload-key []
                             load-key [])]
    (update-in state-tracker
               [:clojure.tools.namespace.track/deps :dependents]
               (fn [m]
                 (into {}
                       (map (fn [[k v]] [k (apply disj v unloaded)]) m))))))
```

Before spending the time to create a proper pull request, is this approach worth pursuing?

**Comment by marick** [comment]
Sorry for the delay. I think that makes sense and I think it's worth giving it a try. It'll need some trial-through-use, since I'm pretty sure I didn't forget about deleted namespaces: rather, things broke when I tried to use tools.namespace for that. However, that was years ago. I don't remember the problem, and it could well have gone away on its own. 

If you make a pull request, I'll use that version.
