### ISSUE TITLE
Filtering clojure.test tests with midje autotest

### ISSUE THREAD

**Issue by drorbemet** [marick/Midje#341]
## Selecting clojure.test tests:
- Define test  selectors in project.clj but only for clojure.test tests?
```
:test-selectors {:default (complement :integration)
                 :integration :integration
                 :all (constantly true)}
```
- Group tests:
```
(deftest a-unit-test
  (is (= true true))

(deftest ^:integration network-heavy-test
  (is (= true true))
```

- Select Groups and run the tests using lein test:

lein test :integration
lein test :default
lein test :all

## Selecting Groups and run the tests using midje 
```(autotest :filters :default)```
This doesn't seem to filter the clojure.test tests. Did I miss something here?

**Comment by retnuh** [comment]
It's a real pain that the filters don't exclude core.test tests; I'm trying to migrate to midje, and want to use autotest to  just check my facts, not run my tests...

**Comment by marick** [comment]
I can't do what you want, but I can do something that's probably useful.

The problem is that clojure.test selectors aren't part of clojure.test. They're added on by Leiningen. In order for Midje to replicate that behavior, it would have to include some (rather kludgy) code like that in https://github.com/technomancy/leiningen/blob/master/src/leiningen/test.clj - and it would now have to track changes to Leiningen. I wouldn't necessarily turn down a pull request, but...

For your purposes, I hope it's tolerable for autotest to simply ignore clojure.test tests, and leave running those to the less frequent `lein midje`. As of 1.9.0-SNAPSHOT, you can do that like this:

* Put `(change-defaults :run-clojure-test false)` in your .midje.clj
* Omit that line from a configuration file that you use with `lein midje :config <configfile>

I'm having trouble deploying the new version to snapshot. I'll add a comment when I succeed.

**Comment by retnuh** [comment]
That certainly helps in my case, thanks!  Not sure about OP though...

**Comment by marick** [comment]
I was able to deploy the snapshot.
