### ISSUE TITLE
Metadata (or other) filtering on clojure.test tests

### ISSUE THREAD

**Issue by avandras** [marick/Midje#354]
I've tried to find a way to apply all the filtering goodies to tests that are around from earlier and are written using clojure.test.  Defining metadata there does not help - apparently, that metadata on `(deftest)` is not 'translated' to midje metadata.  What is slightly more surprising, the description given to `(testing)` is also not considered like a fact name.

Is there a way to achieve filtering of those old tests?  If not, I'd be happy to see this marked as a whishlist item.

**Comment by marick** [comment]
A lot of the problem is that a good deal of what people consider "clojure.test" is actually partially implemented by `lein test`, which has a lot of code to compensate for the fact that clojure.test is an impoverished and stagnant codebase. 

It could have been better - I'd hoped at the first Clojure Conj for different framework authors to work on an single underlying API that we could all build on. That got shot down, so more than trivial interoperability isn't going to happen.

Yeah, it's a missed opportunity.
