### ISSUE TITLE
Do not test on namespace load

### ISSUE THREAD

**Issue by PetrGlad** [marick/Midje#372]
I have `midje.sweet/fact`s  defined on top level. This causes tests to be executed each time namespace is loaded. Is this expected? Why?

What is suggested way to declare my Midje tests so they are only executed when tests are requested (e.g. when I examine them in REPL or launch "lein midje")? I want to avoid side-effects on namespace load since this interferes with code analyzers e.g. Eastwood's Leiningen plugin or namespace loading tools like `clojure.tools.namespace`.

**Comment by marick** [comment]
It is expected. It's that way because I like that test namespaces that have non-test code in them execute as they read. (That is, that you are free to use whatever forms you want before a `fact`.) That's a bad idea in theory, but I find it makes for more understandable test namespaces in practice.

To change that, set the [configuration option](https://github.com/marick/Midje/wiki/Configuration-files) `:check-after-creation` to `false`. You can then use [check-facts](https://github.com/marick/Midje/wiki/The-compendium) to run the tests.
