### ISSUE TITLE
Exceptions thrown in equals are swallowed

### ISSUE THREAD

**Issue by AlexBaranosky** [marick/Midje#87]
This makes finding bugs in your equality code tough.  Could we allow exceptions thrown in extended-= to bubble up?  Or possibly let them be wrapped in a CapturedException, so that Midje can continue to run the rest of the facts.

**Comment by phillipm** [comment]
closing because there is nothing actionable in this issue.
I do wonder if the change from catching `Throwable`s to catching `Exception`s in https://github.com/marick/Midje/pull/440/files#diff-7f260785c3b772fc42a0dd1009dbff44R50 addresses this issue in any way. This came about because I found that equality checking was swallowing errors that would be useful to show the user (more context in that PR description)
